// src/app/layout.js
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'; // Import your global CSS
import NavbarPage from './navbar/page';
import Footer  from './footer/page';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'BytiBits',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="row "  style={{width:'95%',  margin:'auto', padding:'0'}}>  
      <NavbarPage />
      </div>
      <div className="row "  style={{width:'95%',  margin:'auto', padding:'4rem 0', backgroundColor:'#f4Efec', borderRadius:'100px 100px 0 0', marginBottom:'2rem'}}>   
      {children}
<Footer />
      </div>
      </body>
  
    </html>
  );
}
